; ESP32 蜂箱多传感器数据采集与局域网展示教学原型
[env:esp32dev]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    claws/BH1750@^1.3.0
    adafruit/Adafruit BMP280 Library@^2.6.8
    bblanchon/ArduinoJson@^6.21
